apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: swlabpods-deny-external-traffic
spec:
  podSelector:
    matchLabels:
      kubessh: userpods
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 203.250.32.0/19
