apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: swlabpods-deny-external-traffic
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 203.250.30.0/24
          - 203.250.31.0/24
          - 203.250.32.0/22
          - 203.250.36.0/24
